CREATE TABLE IF NOT EXISTS staff_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('new_lead')),
  conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read_at TIMESTAMPTZ,
  UNIQUE (type, conversation_id)
);

CREATE INDEX IF NOT EXISTS idx_staff_notifications_unread
  ON staff_notifications (created_at DESC, id DESC)
  WHERE read_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_messages_inbound_latest
  ON messages (conversation_id, created_at DESC, id DESC)
  WHERE direction = 'IN';

CREATE INDEX IF NOT EXISTS idx_messages_outbound_sent_latest
  ON messages (conversation_id, created_at DESC, id DESC)
  WHERE direction = 'OUT' AND send_status = 'SENT';
