CREATE TABLE IF NOT EXISTS quotation_counters (
  year INTEGER PRIMARY KEY,
  last_number INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS quotations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES conversations(id),
  number TEXT NOT NULL,
  revision INTEGER NOT NULL DEFAULT 0,
  supersedes_id BIGINT REFERENCES quotations(id),
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'SUPERSEDED', 'CANCELLED')),
  title TEXT NOT NULL DEFAULT '',
  buyer_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  seller_json JSONB,
  valid_days INTEGER NOT NULL DEFAULT 30,
  issue_date TEXT,
  valid_until TEXT,
  discount_satang BIGINT NOT NULL DEFAULT 0,
  vat_rate_bp INTEGER NOT NULL DEFAULT 0,
  withholding_rate_bp INTEGER NOT NULL DEFAULT 300,
  subtotal_satang BIGINT NOT NULL DEFAULT 0,
  vat_satang BIGINT NOT NULL DEFAULT 0,
  total_satang BIGINT NOT NULL DEFAULT 0,
  withholding_satang BIGINT NOT NULL DEFAULT 0,
  payment_terms TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  public_token TEXT UNIQUE,
  decision_name TEXT,
  decision_reason TEXT,
  decided_at TIMESTAMPTZ,
  decision_read_at TIMESTAMPTZ,
  created_by TEXT NOT NULL,
  sent_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (number, revision)
);

CREATE TABLE IF NOT EXISTS quotation_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_id BIGINT NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  description TEXT NOT NULL,
  quantity_hundredths BIGINT NOT NULL,
  unit TEXT NOT NULL DEFAULT '',
  unit_price_satang BIGINT NOT NULL,
  amount_satang BIGINT NOT NULL,
  UNIQUE (quotation_id, position)
);

CREATE INDEX IF NOT EXISTS idx_quotations_conversation ON quotations(conversation_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quotations_updated ON quotations(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_quotations_unread_decisions ON quotations(decided_at DESC) WHERE decided_at IS NOT NULL AND decision_read_at IS NULL;
