function loadConfig(env = process.env) {
  const nodeEnv = env.NODE_ENV || 'development';
  if (nodeEnv === 'production' && !env.DATABASE_URL) {
    throw new Error('Production requires DATABASE_URL');
  }
  if (env.DATABASE_URL && !/^postgres(?:ql)?:\/\//i.test(env.DATABASE_URL)) {
    throw new Error('DATABASE_URL must be a PostgreSQL connection string');
  }
  if (nodeEnv === 'production' && (!env.LINE_CHANNEL_SECRET || !env.LINE_CHANNEL_ACCESS_TOKEN || !env.STAFF_PASSWORD_HASH)) {
    throw new Error('Production requires LINE_CHANNEL_SECRET, LINE_CHANNEL_ACCESS_TOKEN, and STAFF_PASSWORD_HASH');
  }
  if (nodeEnv === 'production' && !/^scrypt\$[a-f0-9]{32}\$[a-f0-9]{128}$/i.test(env.STAFF_PASSWORD_HASH || '')) {
    throw new Error('STAFF_PASSWORD_HASH must be generated by scripts/hash-password.js');
  }
  if (env.LIFF_ID && !/^\d+-[A-Za-z0-9]+$/.test(env.LIFF_ID)) throw new Error('LIFF_ID must look like 1234567890-AbCdEfGh');
  const port = Number(env.PORT || 3000);
  if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error('PORT must be an integer from 1 to 65535');

  return {
    nodeEnv,
    isProduction: nodeEnv === 'production',
    port,
    databaseUrl: env.DATABASE_URL || '',
    lineChannelSecret: env.LINE_CHANNEL_SECRET || '',
    lineAccessToken: env.LINE_CHANNEL_ACCESS_TOKEN || '',
    staffUsername: env.STAFF_USERNAME || 'admin',
    staffPasswordHash: env.STAFF_PASSWORD_HASH || '',
    fakeLineMode: env.LINE_FAKE_MODE === 'true' && nodeEnv !== 'production',
    publicBaseUrl: env.PUBLIC_BASE_URL || 'http://localhost:3000',
    liffId: env.LIFF_ID || '',
    richMenuImagePath: env.RICH_MENU_IMAGE_PATH || pathFromRepo('assets/line-rich-menu-2500x1686.jpg'),
  };
}

function pathFromRepo(relativePath) {
  return require('node:path').resolve(__dirname, '..', relativePath);
}

module.exports = { loadConfig };
